### ISSUE TITLE
any update??

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [VaheSaroyan/react-native-image-editor#1]
Getting errors in new react native versions. Please update this package with new code.

**Comment by VaheSaroyan** [comment]
Hi @SMARTMICROWORLD i will try to update it in a few days

**Comment by SMARTMICROWORLD** [comment]
> Hi @SMARTMICROWORLD i will try to update it in a few days

I have created memes app in react native but I want image editing features like - https://play.google.com/store/apps/details?id=com.memes.plus and I think your photo editor is helpful. If you can modify it like memes app I will be so thankful to you and also can pay you if my app gets paid in future. Thanks

**Comment by VaheSaroyan** [comment]
sorry for late answer im very busy , but today i will try to did finish
update related lib

пн, 18 мар. 2024 г. в 11:39, Smart micro WORLD ***@***.***>:

**Comment by VaheSaroyan** [comment]
resolved
